import { prisma } from '../../config/database';
import PDFDocument from 'pdfkit';
import { Response } from 'express';

export const reportService = {
    async generatePatientPDF(patientId: string, res: Response): Promise<void> {
        const patient = await prisma.patient.findUnique({
            where: { id: patientId },
            include: {
                admissions: { orderBy: { admittedAt: 'desc' }, take: 5, include: { clinicalData: true } },
                mlPredictions: { orderBy: { createdAt: 'desc' }, take: 1 },
                careRecommendations: { include: { items: true }, orderBy: { generatedAt: 'desc' }, take: 1 },
                alerts: { where: { isResolved: false }, orderBy: { createdAt: 'desc' } },
            },
        });

        if (!patient) throw new Error('Patient not found');

        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="patient-${patient.patientCode}.pdf"`);
        doc.pipe(res);

        // Header
        doc.fontSize(22).fillColor('#0A0E1A').text('MediSense AI', { align: 'center' });
        doc.fontSize(14).fillColor('#555').text('Patient Clinical Report', { align: 'center' });
        doc.moveDown();

        // Patient information
        doc.fontSize(16).fillColor('#0A0E1A').text('Patient Information');
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(0.5);

        const dob = new Date(patient.dateOfBirth);
        const age = Math.floor((Date.now() - dob.getTime()) / (365.25 * 24 * 3600000));

        doc.fontSize(11).fillColor('#333');
        doc.text(`Patient Code: ${patient.patientCode}  |  Name: ${patient.firstName} ${patient.lastName}`);
        doc.text(`Age: ${age}  |  Gender: ${patient.gender}  |  Blood Group: ${patient.bloodGroup || 'Unknown'}`);
        doc.text(`BMI: ${patient.bmi || 'N/A'}  |  Risk Level: ${patient.currentRiskLevel}  |  Risk Score: ${patient.riskScore.toFixed(1)}`);
        doc.moveDown();

        // Comorbidities
        const comorbidities = [
            patient.hasDiabetes && 'Diabetes',
            patient.hasHypertension && 'Hypertension',
            patient.hasHeartDisease && 'Heart Disease',
            patient.hasCKD && 'CKD',
            patient.hasAsthma && 'Asthma',
            patient.hasCOPD && 'COPD',
            patient.hasObesity && 'Obesity',
            patient.hasCancer && 'Cancer',
        ].filter(Boolean);

        doc.text(`Comorbidities: ${comorbidities.length ? comorbidities.join(', ') : 'None'}`);
        doc.moveDown();

        // Latest prediction
        const pred = patient.mlPredictions[0];
        if (pred) {
            doc.fontSize(16).fillColor('#0A0E1A').text('Latest ML Prediction');
            doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
            doc.moveDown(0.5);
            doc.fontSize(11).fillColor('#333');
            doc.text(`Risk Level: ${pred.predictedRiskLevel}  |  Confidence: ${(pred.riskConfidence * 100).toFixed(1)}%`);
            doc.text(`Readmission Risk: ${pred.readmissionRisk ? 'Yes' : 'No'}  |  Probability: ${(pred.readmissionProbability * 100).toFixed(1)}%`);
            doc.text(`Predicted LOS: ${pred.predictedLengthOfStay.toFixed(1)} days`);
            doc.text(`Cluster: ${pred.clusterName}`);
            doc.moveDown();
        }

        // Active alerts
        if (patient.alerts.length > 0) {
            doc.fontSize(16).fillColor('#C0392B').text('Active Alerts');
            doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
            doc.moveDown(0.5);
            doc.fontSize(11);
            patient.alerts.slice(0, 5).forEach(alert => {
                doc.fillColor('#C0392B').text(`[${alert.severity}] ${alert.type}: ${alert.message}`);
            });
            doc.moveDown();
        }

        // Footer
        doc.fontSize(9).fillColor('#888').text(
            `Generated by MediSense AI on ${new Date().toLocaleString()} | CONFIDENTIAL`,
            { align: 'center' }
        );

        doc.end();
    },
};
