import path from 'path';
import fs from 'fs';
import { Response } from 'express';
import { prisma } from '../../config/database';
import { AppError } from '../../utils/apiResponse';
import { emitLabReportUploaded } from '../../config/socket';
import { notificationService } from '../notifications/notification.service';
import { LAB_REPORTS_DIR } from '../../middleware/upload.middleware';

/**
 * `LabTestResult.fileUrl` stores only the internal disk filename (a random
 * UUID, set by upload.middleware.ts) — never a directly-fetchable URL. The
 * only way to actually retrieve the bytes is the ownership-checked
 * GET /lab/reports/:id/file route below, so this helper computes the
 * public-facing download URL callers (frontend) should use instead of the
 * raw filename.
 */
function withDownloadUrl<T extends { id: string; result?: { fileUrl: string | null } | null }>(request: T) {
    if (!request.result?.fileUrl) return request;
    return { ...request, result: { ...request.result, downloadUrl: `/api/v1/lab/${request.id}/reports/file` } };
}

export const labService = {

    /** Lab tech: upload a PDF report (stores the internal disk filename only) */
    async uploadPdfReport(requestId: string, diskFilename: string, technicianNote?: string) {
        const req = await prisma.labTestRequest.findUnique({
            where: { id: requestId },
            include: {
                patient: { select: { id: true, firstName: true, lastName: true, userId: true, patientCode: true } },
            },
        });
        if (!req) throw new AppError('Lab test request not found', 404, 'NOT_FOUND');

        // Upsert result — fileUrl holds the internal disk filename, not a public URL.
        const result = await prisma.labTestResult.upsert({
            where: { requestId },
            update: { fileUrl: diskFilename, rawValues: { note: technicianNote } },
            create: { requestId, fileUrl: diskFilename, rawValues: { note: technicianNote }, aiAnalysis: {} },
        });

        await prisma.labTestRequest.update({
            where: { id: requestId },
            data: { status: 'COMPLETED' },
        });

        // Real-time + persistent notification to patient — only the
        // authenticated download URL is sent, never the raw filename.
        const downloadUrl = `/api/v1/lab/${requestId}/reports/file`;
        const patientUserId = req.patient.userId;
        if (patientUserId) {
            emitLabReportUploaded(patientUserId, {
                requestId,
                testId: req.testId,
                testType: req.testType,
                downloadUrl,
                patientName: `${req.patient.firstName} ${req.patient.lastName}`,
            });
            await notificationService.create(
                patientUserId,
                '🧪 Lab Report Ready!',
                `Your ${req.testType.replace('_', ' ')} report is ready. You can download it from your Lab Reports section.`,
                'SUCCESS',
                { labTestRequestId: requestId, downloadUrl },
            );
        }

        return { result: { ...result, downloadUrl }, testId: req.testId, testType: req.testType };
    },

    /** Streams a report's PDF after the caller's ownership has already been verified by requireOwnership. */
    async streamReportFile(requestId: string, res: Response) {
        const result = await prisma.labTestResult.findUnique({
            where: { requestId },
            select: { fileUrl: true },
        });
        if (!result?.fileUrl) throw new AppError('Report file not found', 404, 'NOT_FOUND');

        // fileUrl is always a bare UUID-based filename generated by
        // upload.middleware.ts — never attacker-controlled — but resolve
        // and confirm containment defensively before touching the filesystem.
        const filePath = path.join(LAB_REPORTS_DIR, path.basename(result.fileUrl));
        if (!filePath.startsWith(LAB_REPORTS_DIR) || !fs.existsSync(filePath)) {
            throw new AppError('Report file not found', 404, 'NOT_FOUND');
        }
        res.setHeader('Content-Type', 'application/pdf');
        res.sendFile(filePath);
    },


    async createRequest(data: {
        patientId: string;
        consultationId?: string;
        orderedByDocId: string;
        testType: string;
        priority?: string;
        notes?: string;
    }) {
        const count = await prisma.labTestRequest.count();
        const testId = `TEST-${String(count + 1).padStart(4, '0')}`;
        return prisma.labTestRequest.create({
            data: {
                testId,
                patientId: data.patientId,
                consultationId: data.consultationId,
                orderedByDocId: data.orderedByDocId,
                testType: data.testType as any,
                priority: data.priority || 'NORMAL',
                notes: data.notes,
                status: 'PENDING',
            },
            include: {
                patient: { select: { id: true, firstName: true, lastName: true, patientCode: true } },
            },
        });
    },

    async getPending() {
        const requests = await prisma.labTestRequest.findMany({
            where: { status: { in: ['PENDING', 'ACCEPTED', 'SAMPLE_COLLECTED'] } },
            include: {
                patient: { select: { id: true, firstName: true, lastName: true, patientCode: true, phone: true } },
                result: true,
            },
            orderBy: [{ priority: 'asc' }, { createdAt: 'asc' }],
        });
        return requests.map(withDownloadUrl);
    },

    async getAll(filters?: { patientId?: string; status?: string }) {
        const requests = await prisma.labTestRequest.findMany({
            where: {
                ...(filters?.patientId && { patientId: filters.patientId }),
                ...(filters?.status && { status: filters.status as any }),
            },
            include: {
                patient: { select: { id: true, firstName: true, lastName: true, patientCode: true } },
                result: true,
            },
            orderBy: { createdAt: 'desc' },
        });
        return requests.map(withDownloadUrl);
    },

    async getById(id: string) {
        const req = await prisma.labTestRequest.findUnique({
            where: { id },
            include: {
                patient: { select: { id: true, firstName: true, lastName: true, patientCode: true, phone: true } },
                result: true,
            },
        });
        if (!req) throw new AppError('Lab test request not found', 404, 'NOT_FOUND');
        return withDownloadUrl(req);
    },

    async accept(id: string) {
        return prisma.labTestRequest.update({
            where: { id },
            data: { status: 'ACCEPTED' },
            include: { patient: { select: { id: true, firstName: true, lastName: true, patientCode: true } } },
        });
    },

    async markSampleCollected(id: string) {
        return prisma.labTestRequest.update({
            where: { id },
            data: { status: 'SAMPLE_COLLECTED' },
        });
    },

    async uploadResult(requestId: string, data: {
        hemoglobin?: number;
        wbc?: number;
        platelets?: number;
        rbc?: number;
        glucose?: number;
        cholesterol?: number;
        creatinine?: number;
        rawValues?: Record<string, any>;
        fileUrl?: string;
    }) {
        // AI Analysis — flag abnormal values
        const aiAlerts: string[] = [];
        const REF = {
            hemoglobin: { low: 12, high: 17, label: 'Hemoglobin' },
            wbc: { low: 4.0, high: 11.0, label: 'WBC' },
            platelets: { low: 150, high: 400, label: 'Platelets' },
            glucose: { low: 70, high: 100, label: 'Glucose (Fasting)' },
            cholesterol: { low: 0, high: 200, label: 'Cholesterol' },
            creatinine: { low: 0.6, high: 1.2, label: 'Creatinine' },
        };
        for (const [key, ref] of Object.entries(REF)) {
            const val = (data as any)[key];
            if (val !== undefined && val !== null) {
                if (val < ref.low) aiAlerts.push(`⚠️ ${ref.label} LOW (${val}) — below ${ref.low}`);
                if (val > ref.high) aiAlerts.push(`⚠️ ${ref.label} HIGH (${val}) — above ${ref.high}`);
            }
        }

        // Possible disease hints from AI
        const hints: string[] = [];
        if (data.platelets && data.platelets < 100) hints.push('Possible Dengue — Platelet very low');
        if (data.wbc && data.wbc > 11) hints.push('Possible Infection / Sepsis — WBC high');
        if (data.hemoglobin && data.hemoglobin < 10) hints.push('Anemia detected');
        if (data.glucose && data.glucose > 126) hints.push('Possible Diabetes — Glucose elevated');

        const aiAnalysis = { alerts: aiAlerts, hints, analyzedAt: new Date().toISOString() };

        const result = await prisma.labTestResult.create({
            data: {
                requestId,
                hemoglobin: data.hemoglobin,
                wbc: data.wbc,
                platelets: data.platelets,
                rbc: data.rbc,
                glucose: data.glucose,
                cholesterol: data.cholesterol,
                creatinine: data.creatinine,
                rawValues: data.rawValues || {},
                fileUrl: data.fileUrl,
                aiAnalysis,
            },
        });

        await prisma.labTestRequest.update({
            where: { id: requestId },
            data: { status: 'COMPLETED' },
        });

        return { result, aiAnalysis };
    },
};
